# Generated by Django 5.1.7 on 2025-03-09 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educationalopportunities', '0001_initial'),
        ('legalresources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='educationalopportunities.educationalopportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-favorited_at',),
                'unique_together': {('user', 'opportunity')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='legalresources.legalresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-favorited_at',),
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
